name: tensorflow
channels:
  - apple
  - conda-forge
dependencies:
    - python=3.9
    - pip>=19.0
    - jupyter
    - tensorflow-deps
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - ipykernel
    - nltk==3.7
    - keras-preprocessing

    - pip:
      - tensorflow-macos
      - tensorflow-metal

      - -r requirements.txt
        