name: tensorflow
channels:
  - apple
  - conda-forge
dependencies:
    - python=3.9
    - pip>=19.0
    - jupyter
    - tensorflow-deps
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - ipykernel
    - nltk==3.7
    - pip:
      - tensorflow-macos
      - tensorflow-metal
      - tensorflow-text @ https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/download/v2.8/tensorflow_text-2.8.2-cp39-cp39-macosx_11_0_arm64.whl
      - bayesian-optimization
      - gym
      - kaggle
      - wget
      - datasets==1.18.1
        # - -r requirements.txt
        